site_name: Documentation

nav:
  - Home: index.md
  - Model train pipeline: train_model.md

theme: material

plugins:
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
