site_name: Documentation

nav:
  - Home: index.md
  - Model training diagram: train_model.md

theme: material

plugins:
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true

markdown_extensions:
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
