# sweep_config.yaml
# Configuration for Weights & Biases hyperparameter sweep

program: ./src/scennia/train_model.py
project: scennia
method: bayes  # or 'grid', 'random'

metric:
  name: test_f1
  goal: maximize

parameters:
  csv_path:
    value: /shared-data/scennia/lactate-processed/dataset.csv

  model_name:
    values: [resnet18, resnet50, efficientnet_b0, efficientnet_b1]

  batch_size:
    values: [16, 32, 64]

  img_size:
    values: [64, 128, 224]

  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-2

  weight_decay:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-2

  unfreeze_epochs:
    values: [0, 5, 10, 15]

  unfreeze_lr_reduction:
    distribution: uniform
    min: 0.1
    max: 1.0

  use_class_weights:
    values: [true, false]

  loss_patience:
    values: [5, 7, 10]

  f1_patience:
    values: [5, 7, 10]

  max_epochs:
    value: 20  # Fixed for sweep

# Early termination
early_terminate:
  type: hyperband
  min_iter: 5
